- id: strip-exif
  name: strip-exif
  description: This hook ensures that no image metadata (EXIF) is present on images added to version control.
  entry: strip-exif
  language: python
  types: [image]
