- id: strip-exif
  name: strip EXIF metadata
  description: |
    This hook ensures that no image metadata (EXIF) is present on images added to version control.
  entry: exif-stripper
  language: python
  types: [image]
